# docker-compose.yml
version: "3.8"
services:
  main_program:
    build: .

#  second_program:
#    build: .

  postgres:
    image: postgres:10.4

    volumes:
      - type: bind
        source: ./database
        target: /var/lib/postgresql/data/

    ports:
      - "35432:5432"
    environment:
          - DATABASE=gp_makasa
          - USER=${USER}
          - PASS=${PASS}
          - HOST=${HOST}
